// Re-export all tables from the tables directory
// This file is kept for backward compatibility
export {
  activityLogs,
  branches,
  categories,
  companies,
  contacts,
  customers,
  defaultId,
  enrollments,
  invoices,
  masterItems,
  payments,
  permissions,
  productPrices,
  productPricings,
  productSchedules,
  products,
  rolePermissions,
  roles,
  softDelete,
  storageFiles,
  students,
  teacherProducts,
  teachers,
  timestamps,
  users,
} from './tables/index'
