import { eq } from 'drizzle-orm'

import * as schema from '../schema'
import { db } from './client'

const { contacts, customers } = schema

// From web/src/data/contacts.ts (simplified to match schema)
// `customerId` is a demo key resolved against the customer map, not a literal
// DB value. `id` is only used within this file to build the returned map.
const CONTACTS = [
  {
    id: 'con1',
    customerId: 'c1',
    name: 'Hendra Wijaya',
    position: 'Direktur',
    whatsapp: '628111234567',
    email: 'hendra@majubersama.co.id',
    gender: 'male',
    birthPlace: 'Jakarta',
    dateOfBirth: '1975-03-12',
    religion: 'Islam',
    education: 'S1 Teknik Sipil',
    address: 'Jl. Melati No. 10, Jakarta Selatan',
    spouseName: 'Siti Wijaya',
    spouseOccupation: 'Ibu Rumah Tangga',
    childrenNames: 'Andi Wijaya, Budi Wijaya',
    childrenOccupation: 'Mahasiswa, Pelajar SMA',
    profiling: 'Suka golf setiap Sabtu pagi, lebih responsif dihubungi siang hari.',
    isPrimary: true,
    notes: 'Suka golf tiap Sabtu pagi, ramah tapi tegas soal harga.',
  },
  {
    id: 'con2',
    customerId: 'c1',
    name: 'Dewi Kusuma',
    position: 'Manager Keuangan',
    whatsapp: '628112222222',
    email: 'dewi@majubersama.co.id',
    gender: 'female',
    birthPlace: 'Bandung',
    dateOfBirth: '1982-07-20',
    religion: 'Kristen',
    education: 'S1 Akuntansi',
    address: 'Jl. Kebon Jeruk No. 5, Jakarta Barat',
    spouseName: 'Tono Kusuma',
    spouseOccupation: 'Wiraswasta',
    childrenNames: 'Clara Kusuma',
    childrenOccupation: 'Pelajar SD',
    profiling: 'Detail soal administrasi, komunikasi lebih baik lewat email.',
    isPrimary: false,
    notes: 'Detail soal administrasi, minta invoice selalu lengkap.',
  },
  {
    id: 'con3',
    customerId: 'c2',
    name: 'Andi Saputra',
    position: 'CEO',
    whatsapp: '628221234567',
    email: 'andi@teknologinusantara.id',
    gender: 'male',
    birthPlace: 'Surabaya',
    dateOfBirth: '1978-11-05',
    religion: 'Islam',
    education: 'S2 Manajemen',
    address: 'Jl. Pemuda No. 22, Surabaya',
    spouseName: 'Rina Saputra',
    spouseOccupation: 'Dokter',
    childrenNames: 'Dimas Saputra, Eka Saputra',
    childrenOccupation: 'Mahasiswa, Mahasiswa',
    profiling: 'Fokus pada ROI, suka diskusi teknis mendalam.',
    isPrimary: true,
  },
  {
    id: 'con4',
    customerId: 'c4',
    name: 'Rini Susanti',
    position: 'HRD Manager',
    whatsapp: '628441234567',
    email: 'rini@anekacorp.com',
    gender: 'female',
    birthPlace: 'Yogyakarta',
    dateOfBirth: '1985-02-14',
    religion: 'Islam',
    education: 'S1 Psikologi',
    address: 'Jl. Malioboro No. 8, Yogyakarta',
    spouseName: 'Agus Susanto',
    spouseOccupation: 'PNS',
    childrenNames: 'Fira Susanti',
    childrenOccupation: 'Balita',
    profiling: 'Prioritaskan kecepatan respons, aktif di WhatsApp.',
    isPrimary: true,
  },
  {
    id: 'con5',
    customerId: 'c5',
    name: 'Bapak Suroto',
    position: 'Kepala Dinas',
    gender: 'male',
    birthPlace: 'Bandung',
    dateOfBirth: '1968-09-01',
    religion: 'Islam',
    education: 'S1 Administrasi Negara',
    address: 'Jl. Ambon No. 3, Bandung',
    spouseName: 'Ibu Suroto',
    spouseOccupation: 'Guru',
    childrenNames: 'Rudi Suroto, Sari Suroto',
    childrenOccupation: 'PNS, Mahasiswa',
    profiling: 'Formal, lebih suka surat resmi dan pertemuan terjadwal.',
    isPrimary: true,
  },
  {
    id: 'con6',
    customerId: 'c6',
    name: 'Kevin Pratama',
    position: 'Co-Founder',
    whatsapp: '628661234567',
    email: 'kevin@innovasi.id',
    gender: 'male',
    birthPlace: 'Jakarta',
    dateOfBirth: '1990-05-25',
    religion: 'Kristen',
    education: 'S1 Teknik Informatika',
    address: 'Jl. Kaliurang KM 6, Yogyakarta',
    profiling: 'Masih single, startup-minded, cepat ambil keputusan.',
    isPrimary: true,
  },
  {
    id: 'con7',
    customerId: 'c8',
    name: 'Ibu Hartini',
    position: 'Sekretaris',
    gender: 'female',
    birthPlace: 'Jakarta',
    dateOfBirth: '1972-12-30',
    religion: 'Islam',
    education: 'SMA',
    address: 'Jl. Cikini Raya No. 7, Jakarta Pusat',
    spouseName: 'Bapak Hartono',
    spouseOccupation: 'Pensiunan',
    childrenNames: 'Hartini Jr',
    childrenOccupation: 'Pegawai Swasta',
    profiling: 'Suka ngobrol santai sebelum masuk ke topik bisnis.',
    isPrimary: true,
  },
  {
    id: 'con8',
    customerId: 'c9',
    name: 'Ir. Bambang S.',
    position: 'Direktur Utama',
    whatsapp: '628991234567',
    email: 'bambang@megakons.co.id',
    gender: 'male',
    birthPlace: 'Surabaya',
    dateOfBirth: '1965-04-18',
    religion: 'Islam',
    education: 'S1 Teknik Sipil',
    address: 'Jl. Basuki Rahmat No. 102, Surabaya',
    spouseName: 'Hj. Siti Bambang',
    spouseOccupation: 'Ibu Rumah Tangga',
    childrenNames: 'Bambang Jr, Wati Bambang',
    childrenOccupation: 'Pengusaha, Dokter',
    profiling: 'Senior, suka didekati formal dan sopan, keputusan lambat tapi loyal.',
    isPrimary: true,
  },
  {
    id: 'con9',
    customerId: 'c9',
    name: 'Andi Saputra',
    position: 'Konsultan Proyek',
    whatsapp: '628221234567',
    email: 'andi@megakons.co.id',
    gender: 'male',
    birthPlace: 'Surabaya',
    dateOfBirth: '1978-11-05',
    religion: 'Islam',
    education: 'S2 Manajemen',
    address: 'Jl. Pemuda No. 22, Surabaya',
    spouseName: 'Rina Saputra',
    spouseOccupation: 'Dokter',
    childrenNames: 'Dimas Saputra, Eka Saputra',
    childrenOccupation: 'Mahasiswa, Mahasiswa',
    profiling: 'Fokus pada ROI, suka diskusi teknis mendalam.',
    isPrimary: false,
  },
  {
    id: 'con10',
    customerId: 'c6',
    name: 'Rini Susanti',
    position: 'Advisor',
    whatsapp: '628441234567',
    email: 'rini@innovasi.id',
    gender: 'female',
    birthPlace: 'Yogyakarta',
    dateOfBirth: '1985-02-14',
    religion: 'Islam',
    education: 'S1 Psikologi',
    address: 'Jl. Malioboro No. 8, Yogyakarta',
    spouseName: 'Agus Susanto',
    spouseOccupation: 'PNS',
    childrenNames: 'Fira Susanti',
    childrenOccupation: 'Balita',
    profiling: 'Prioritaskan kecepatan respons, aktif di WhatsApp.',
    isPrimary: false,
  },
  {
    id: 'con11',
    customerId: 'c2',
    name: 'Hendra Wijaya',
    position: 'Komisaris',
    whatsapp: '628111234567',
    email: 'hendra@teknologinusantara.id',
    gender: 'male',
    birthPlace: 'Jakarta',
    dateOfBirth: '1975-03-12',
    religion: 'Islam',
    education: 'S1 Teknik Sipil',
    address: 'Jl. Melati No. 10, Jakarta Selatan',
    spouseName: 'Siti Wijaya',
    spouseOccupation: 'Ibu Rumah Tangga',
    childrenNames: 'Andi Wijaya, Budi Wijaya',
    childrenOccupation: 'Mahasiswa, Pelajar SMA',
    profiling: 'Suka golf setiap Sabtu pagi, lebih responsif dihubungi siang hari.',
    isPrimary: false,
  },
  {
    id: 'con12',
    customerId: 'c3',
    name: 'Budi Santoso',
    position: 'Pemilik',
    whatsapp: '628331234567',
    gender: 'male',
    birthPlace: 'Jakarta',
    dateOfBirth: '1980-06-15',
    religion: 'Islam',
    education: 'S1 Arsitektur',
    address: 'Jl. Panjang No. 9, Jakarta Barat',
    spouseName: 'Lina Santoso',
    spouseOccupation: 'Guru',
    childrenNames: 'Dito Santoso',
    childrenOccupation: 'Pelajar SMP',
    profiling: 'Budget-conscious, suka nego harga.',
    isPrimary: true,
  },
  {
    id: 'con13',
    customerId: 'c7',
    name: 'Siti Rahayu',
    position: 'Pemilik',
    whatsapp: '628771234567',
    gender: 'female',
    birthPlace: 'Surabaya',
    dateOfBirth: '1975-10-10',
    religion: 'Islam',
    education: 'SMA',
    address: 'Jl. Kertajaya No. 21, Surabaya',
    spouseName: 'Bapak Rahayu',
    spouseOccupation: 'Wiraswasta',
    childrenNames: 'Rahayu Jr',
    childrenOccupation: 'Mahasiswa',
    profiling: 'Loyal pelanggan lama, prefer kontak via telepon.',
    isPrimary: true,
  },
  {
    id: 'con14',
    customerId: 'c10',
    name: 'Ahmad Fauzi',
    position: 'Direktur',
    gender: 'male',
    birthPlace: 'Jakarta',
    dateOfBirth: '1970-01-22',
    religion: 'Islam',
    education: 'S1 Teknik Sipil',
    address: 'Jl. Daan Mogot No. 31, Jakarta Barat',
    spouseName: 'Fauziah',
    spouseOccupation: 'Ibu Rumah Tangga',
    childrenNames: 'Fauzi Jr, Nia Fauzi',
    childrenOccupation: 'Pegawai Swasta, Pelajar',
    profiling: 'Hati-hati dalam pengambilan keputusan, perlu beberapa kali follow up.',
    isPrimary: true,
  },
] as const

export async function seedContacts(customerIds: Map<string, string>) {
  const contactIds = new Map<string, string>()
  let total = 0

  for (const { id: demoId, customerId: demoCustomerId, isPrimary, ...contact } of CONTACTS) {
    const customerId = customerIds.get(demoCustomerId)
    if (!customerId) {
      console.log(`  Skipping contact "${contact.name}" - customer ${demoCustomerId} not found`)
      continue
    }

    const existing = await db.query.contacts.findFirst({
      where: (t, { and }) => and(eq(t.customerId, customerId), eq(t.name, contact.name)),
    })
    const contactId = existing
      ? existing.id
      : (
          await db
            .insert(contacts)
            .values({ ...contact, customerId, isPrimary })
            .returning()
        )[0].id
    contactIds.set(demoId, contactId)

    if (isPrimary) {
      await db
        .update(customers)
        .set({ primaryContactId: contactId })
        .where(eq(customers.id, customerId))
    }
    total++
  }

  console.log(`  contacts: ${total} records`)
  return contactIds
}
